prose:
  metadata:
    projects:
      - name: "title"
        field:
          element: "text"
          label: "Title"
      - name: "tags"
        field:
          element: "text"
          label: "Tags"
      - name: "image"
        field:
          element: "text"
          label: "Image"
    scenarios:
      - name: "project"
        field:
          element: "textarea"
          label: "Project"
          help: "Enter the project name and id separated by a comma"
          placeholder: "Project Title, project-id"
      - name: "related"
        field:
          element: multiselect
          label: "Related Scenarios"
          help: "Select base scenarios or type a scenario name and id separated by a comma"
          placeholder: "Scenario Title, scenario-id"
          options: "https://rawgit.com/developmentseed/ifpri-impact-data/master/options/scenarios.js?callback=scenarios"
          alterable: true
      - name: "image"
        field:
          element: "text"
          label: "Image"
      - name: "mapParam"
        field:
          element: multiselect
          label: "Map Parameters"
          help: "Select them from the dropdown or add your own"
          options: "https://rawgit.com/developmentseed/ifpri-impact-data/master/options/params.js?callback=params"
          alterable: true
      - name: "mapDefaultGroup"
        field:
          element: select
          label: "Default Map Group"
          options: "https://rawgit.com/developmentseed/ifpri-impact-data/master/options/groups.js?callback=groups"
      - name: "mapDefaultParam"
        field:
          element: select
          label: "Default Map Parameter"
          options: "https://rawgit.com/developmentseed/ifpri-impact-data/master/options/params.js?callback=params"
