prose:
  metadata:
    projects:
      - name: "title"
        field:
          element: "text"
          label: "Title"
      - name: "tags"
        field:
          element: "text"
          label: "Tags"
      - name: "image"
        field:
          element: "text"
          label: "Image"
    scenarios:
      - name: "project"
        field:
          element: "textarea"
          label: "Project"
          help: "Enter the project name and id separated by a comma"
          placeholder: "Project Title, project-id"
      - name: "related"
        field:
          element: multiselect
          label: "Related Scenarios"
          help: "Select base scenarios or type a scenario name and id separated by a comma"
          placeholder: "Scenario Title, scenario-id"
          options:
            - name: "SSP2-GFDL"
              value: "ssp2_gfdl"
            - name: "SSP2-HGEM"
              value: "ssp2_hgem"
            - name: "SSP2-MIROC"
              value: "ssp2_miroc"
            - name: "SSP2-IPSL"
              value: "ssp2_ipsl"
            - name: "SSP2-NoCC"
              value: "ssp2_nocc"
          alterable: true
      - name: "image"
        field:
          element: "text"
          label: "Image"
      - name: "mapParam"
        field:
          element: multiselect
          label: "Map Parameters"
          help: "Select them from the dropdown or add your own"
          options:
            - name: "Animal Numbers"
              value: "anmlnumxagg"
            - name: "Livestock Feed Demand"
              value: "qlxagg"
            - name: "Total Yield"
              value: "tyldxagg"
            - name: "Animal Yield"
              value: "anmlyldxagg"
            - name: "Food Availability"
              value: "foodavailxagg"
            - name: "Income"
              value: "gdpxagg"
            - name: "Total Demand"
              value: "qdxagg"
            - name: "Export Share of Production"
              value: "qeshxagg"
            - name: "Household Demand"
              value: "qfxagg"
            - name: "Import Share of Demand"
              value: "qmshxagg"
            - name: "Net Trade Share of Production"
              value: "qnsh1xagg"
            - name: "Net Trade Share of Demand"
              value: "qnsh2xagg"
            - name: "Net Trade"
              value: "qnxagg"
            - name: "Commodity Supply"
              value: "qsupxagg"
            - name: "Total Area"
              value: "tareaxagg"
          alterable: true
      - name: "mapDefaultGroup"
        field:
          element: select
          label: "Default Map Group"
          options:
            - name: "Animal Products"
              value: "animal_products"
            - name: "Cereals"
              value: "cereals"
            - name: "Fruits and Vegetables"
              value: "fruits_vegetables"
            - name: "Oils"
              value: "oils"
            - name: "Food Oils"
              value: "food_oils"
            - name: "Oil Seeds"
              value: "oils_seeds"
            - name: "Oil Meals"
              value: "oil_meals"
            - name: "Other"
              value: "other"
            - name: "Pulses"
              value: "pulses"
            - name: "Roots and Tubers"
              value: "roots_tubers"
            - name: "Sugar"
              value: "sugar"
      - name: "mapDefaultParam"
        field:
          element: select
          label: "Default Map Parameter"
          options:
            - name: "Animal Numbers"
              value: "anmlnumxagg"
            - name: "Livestock Feed Demand"
              value: "qlxagg"
            - name: "Total Yield"
              value: "tyldxagg"
            - name: "Animal Yield"
              value: "anmlyldxagg"
            - name: "Food Availability"
              value: "foodavailxagg"
            - name: "Income"
              value: "gdpxagg"
            - name: "Total Demand"
              value: "qdxagg"
            - name: "Export Share of Production"
              value: "qeshxagg"
            - name: "Household Demand"
              value: "qfxagg"
            - name: "Import Share of Demand"
              value: "qmshxagg"
            - name: "Net Trade Share of Production"
              value: "qnsh1xagg"
            - name: "Net Trade Share of Demand"
              value: "qnsh2xagg"
            - name: "Net Trade"
              value: "qnxagg"
            - name: "Commodity Supply"
              value: "qsupxagg"
            - name: "Total Area"
              value: "tareaxagg"
