prose:
  metadata:
    projects:
      - name: "title"
        field:
          element: "text"
          label: "Title"
      - name: "tags"
        field:
          element: "text"
          label: "Tags"
      - name: "image"
        field:
          element: "text"
          label: "Image"
    scenarios:
      - name: "image"
        field:
          element: "text"
          label: "Image"
      - name: "mapParam"
        field:
          element: multiselect
          label: "Map Parameters"
          help: "Select them below or add your own"
          options: "https://rawgit.com/developmentseed/ifpri-impact-data/master/options/mapParams.json?callback=params"
          alterable: true
